version: '3' 

services: 
  app:
    container_name: crypto_charts
    # restart: always
    build: .
    depends_on: 
      - db
    expose: 
      - "3000"
    ports: 
      - "3000:3000" 
    command: npm run start      
  db:
    container_name: "crypto_postgres"
    build: ./ps_docker
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER:vitomadio
    volumes: 
      - ./pg_data:/var/lib/postgresql/data
    
volumes:
  pg_data: